In [29]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve

# 1) Decomposing a matrix using LU decomposition

In [38]:
A = np.array([[2., 5., 8], [5., 2., 2.], [7., 5., 6.]])

In [39]:
A # A matrix

array([[2., 5., 8.],
       [5., 2., 2.],
       [7., 5., 6.]])

In [40]:
def LU(A): ### LU decomposition
    
    n = len(A)
    
    U = np.zeros((n, n))
    L = np.eye(n)
    
    for k in range(n):
        
        U[k, k:] = A[k, k:] - L[k,:k] @ U[:k,k:]
        L[(k+1):,k] = (A[(k+1):,k] - L[(k+1):,:] @ U[:,k]) / U[k, k]
    
    return L, U

In [41]:
a = LU(A)
L = a[0]
U = a[1]

In [42]:
L # L matrix

array([[1.        , 0.        , 0.        ],
       [2.5       , 1.        , 0.        ],
       [3.5       , 1.19047619, 1.        ]])

In [43]:
U # U matrix

array([[  2.        ,   5.        ,   8.        ],
       [  0.        , -10.5       , -18.        ],
       [  0.        ,   0.        ,  -0.57142857]])

In [44]:
L @ U # A=LU

array([[2., 5., 8.],
       [5., 2., 2.],
       [7., 5., 6.]])

In [45]:
A

array([[2., 5., 8.],
       [5., 2., 2.],
       [7., 5., 6.]])

# 2) Properties of LU decomposable matrix

In [9]:
np.linalg.det(A) #det(A)

11.99999999999999

In [46]:
a=1
for i in range(3):
    a=U[i][i]*a

In [47]:
a #u_11 * u_22 * u_33

12.000000000000032

It is close enough

# 3) Using LU decomposition to solve linear equations

In [48]:
w= np.array([[2.], [5.], [-7.]]);w # w vector

array([[ 2.],
       [ 5.],
       [-7.]])

In [49]:
def solve(A,w):  # solving for x
    LU,p = lu_factor(A) 
    return lu_solve((LU,p),w)

In [50]:
solution=solve(A,w);solution # solved x

array([[  8. ],
       [-42. ],
       [ 24.5]])

In [51]:
A @ solution # Ax=w  Checking solution

array([[ 2.],
       [ 5.],
       [-7.]])

In [52]:
w # w vector

array([[ 2.],
       [ 5.],
       [-7.]])